In [1]:
import pandas as pd

In [ ]:
# Read SUBMISSION file into a DataFrame
submission = pd.read_csv(
    'raw_data/2026q1/SUBMISSION.tsv',
    sep='\t', # separator '\t' tells pandas the columns are separated by tabs, not commas (confirmed in Phase 1)
    dtype={'ISSUERCIK': str} # dtype forces specified column to stay as text (str), protecting leading zeros that a number would silently drop
)

# Quick sanity check: how many rows, and what do the first 5 look like?
print(submission.shape)
submission.head()

(69259, 14)

,ACCESSION_NUMBER,FILING_DATE,PERIOD_OF_REPORT,DATE_OF_ORIG_SUB,NO_SECURITIES_OWNED,NOT_SUBJECT_SEC16,FORM3_HOLDINGS_REPORTED,FORM4_TRANS_REPORTED,DOCUMENT_TYPE,ISSUERCIK,ISSUERNAME,ISSUERTRADINGSYMBOL,REMARKS,AFF10B5ONE
0,0001193125-26-134840,31-MAR-2026,27-MAR-2026,NaN,NaN,false,NaN,NaN,4,0001825079,"Velo3D, Inc.",VELO,NaN,false
1,0002060688-26-000006,31-MAR-2026,30-MAR-2026,NaN,NaN,0,NaN,NaN,4,0001874315,Satellogic Inc.,SATL,NaN,0
2,0001104659-26-037685,31-MAR-2026,18-MAR-2026,NaN,0.0,NaN,NaN,NaN,3,0001969302,Pony AI Inc.,PONY,Exhibit 24 - Power of Attorney,NaN
3,0000895345-26-000136,31-MAR-2026,18-MAR-2026,NaN,1.0,NaN,NaN,NaN,3,0000912892,"GRUPO TELEVISA, S.A.B.",TV,NaN,NaN
4,0002123440-26-000001,31-MAR-2026,18-MAR-2026,NaN,1.0,NaN,NaN,NaN,3,0002074123,CCH Holdings Ltd,CCHH,NaN,NaN

In [ ]:
# Read REPORTINGOWNER.tsv into a DataFrame.
# sep='\t' tells pandas the columns are tab-separated, not comma-separated.
# dtype forces RPTOWNERCIK to stay text, protecting leading zeros in this CIK field.
reportingowner = pd.read_csv(
    'raw_data/2026q1/REPORTINGOWNER.tsv',
    sep='\t',
    dtype={'RPTOWNERCIK': str}
)

print(reportingowner.shape)
reportingowner.head()

(72211, 13)

,ACCESSION_NUMBER,RPTOWNERCIK,RPTOWNERNAME,RPTOWNER_RELATIONSHIP,RPTOWNER_TITLE,RPTOWNER_TXT,RPTOWNER_STREET1,RPTOWNER_STREET2,RPTOWNER_CITY,RPTOWNER_STATE,RPTOWNER_ZIPCODE,RPTOWNER_STATE_DESC,FILE_NUMBER
0,0001493152-26-014456,0002125911,Ong Sie Hou Raymond,Director,NaN,NaN,"600 NORTH BRIDGE ROAD,",PARKVIEW SQUARE #24-01,SINGAPORE,NaN,188778,SINGAPORE,001-42426
1,0001213900-26-037919,0002125166,Huang Huaguang,Officer,Chief Financial Officer,NaN,"ROOM 1, BUILDING 10, JINZHONG GUOBIN HUI","QINYUAN 2ND ROAD, XILI STREET",SHENZHEN,NaN,518071,CHINA,001-33768
2,0001193125-26-135334,0001238734,WALKER JOHN KENT,Officer,"President, Global Affairs, CLO",NaN,C/O ALPHABET INC.,1600 AMPHITHEATRE PKWY,MOUNTAIN VIEW,CA,94043,NaN,001-37580
3,0001030471-26-000005,0001432657,Shao Sean,Director,NaN,NaN,"4TH FLOOR, SOUTH WING","368 LIUHE ROAD, BINJIANG DISTRICT",HANGZHOU,NaN,310053,CHINA,001-35216
4,0001062993-26-001774,0002122229,Tavares Craig,Officer,BUZZ HPC- President & COO,NaN,"7900 CALLAGHAN ROAD, SUITE 128",NaN,SAN ANTONIO,TX,78229,NaN,001-40398

In [ ]:
# Read NONDERIV_TRANS.tsv into a DataFrame — same pattern as your last 2 reads
nonderiv_trans = pd.read_csv(
    'raw_data/2026q1/NONDERIV_TRANS.tsv',
    sep='\t'
)

print(nonderiv_trans.shape)
nonderiv_trans.head()

C:\Users\steph\AppData\Local\Temp\ipykernel_37920\736670649.py:2: DtypeWarning: Columns (0: VALU_OWND_FOLWNG_TRANS_FN) have mixed types. Specify dtype option on import or set low_memory=False.
  nonderiv_trans = pd.read_csv(

(103733, 28)

,ACCESSION_NUMBER,NONDERIV_TRANS_SK,SECURITY_TITLE,SECURITY_TITLE_FN,TRANS_DATE,TRANS_DATE_FN,DEEMED_EXECUTION_DATE,DEEMED_EXECUTION_DATE_FN,TRANS_FORM_TYPE,TRANS_CODE,...,TRANS_ACQUIRED_DISP_CD,TRANS_ACQUIRED_DISP_CD_FN,SHRS_OWND_FOLWNG_TRANS,SHRS_OWND_FOLWNG_TRANS_FN,VALU_OWND_FOLWNG_TRANS,VALU_OWND_FOLWNG_TRANS_FN,DIRECT_INDIRECT_OWNERSHIP,DIRECT_INDIRECT_OWNERSHIP_FN,NATURE_OF_OWNERSHIP,NATURE_OF_OWNERSHIP_FN
0,0001193125-26-135334,8937906,Class C Capital Stock,NaN,31-MAR-2026,NaN,NaN,NaN,4.0,G,...,A,NaN,60801.0,NaN,NaN,NaN,I,NaN,NaN,NaN
1,0001193125-26-135334,8937901,Class C Capital Stock,NaN,27-MAR-2026,NaN,NaN,NaN,4.0,S,...,D,NaN,56608.0,NaN,NaN,NaN,I,NaN,"By Arete Trust, John Kent Walker and Diana Rut...",NaN
2,0001193125-26-135334,8937905,Class C Capital Stock,NaN,31-MAR-2026,NaN,NaN,NaN,4.0,G,...,D,NaN,23508.0,NaN,NaN,NaN,D,NaN,"By Arete Trust, John Kent Walker and Diana Rut...",NaN
3,0001193125-26-135334,8937904,Class C Capital Stock,NaN,27-MAR-2026,NaN,NaN,NaN,4.0,S,...,D,NaN,51808.0,NaN,NaN,NaN,I,NaN,"By Arete Trust, John Kent Walker and Diana Rut...",NaN
4,0001193125-26-135334,8937900,Class C Capital Stock,NaN,27-MAR-2026,NaN,NaN,NaN,4.0,S,...,D,NaN,58124.0,NaN,NaN,NaN,I,NaN,"By Arete Trust, John Kent Walker and Diana Rut...",NaN

In [ ]:
# Filter nonderiv_trans down to only Purchase (P) and Sale (S) transactions.

# .isin() checks TRANS_CODE against the list (P&S) and returns True/False per row.
# Outter nonderiv_trans [] is to keep any rows that return True (P & S) and anything else is dropped
nonderiv_trans = nonderiv_trans[nonderiv_trans['TRANS_CODE'].isin(['P', 'S'])]

print(nonderiv_trans.shape)
nonderiv_trans.head()

(28757, 28)

,ACCESSION_NUMBER,NONDERIV_TRANS_SK,SECURITY_TITLE,SECURITY_TITLE_FN,TRANS_DATE,TRANS_DATE_FN,DEEMED_EXECUTION_DATE,DEEMED_EXECUTION_DATE_FN,TRANS_FORM_TYPE,TRANS_CODE,...,TRANS_ACQUIRED_DISP_CD,TRANS_ACQUIRED_DISP_CD_FN,SHRS_OWND_FOLWNG_TRANS,SHRS_OWND_FOLWNG_TRANS_FN,VALU_OWND_FOLWNG_TRANS,VALU_OWND_FOLWNG_TRANS_FN,DIRECT_INDIRECT_OWNERSHIP,DIRECT_INDIRECT_OWNERSHIP_FN,NATURE_OF_OWNERSHIP,NATURE_OF_OWNERSHIP_FN
1,0001193125-26-135334,8937901,Class C Capital Stock,NaN,27-MAR-2026,NaN,NaN,NaN,4.0,S,...,D,NaN,56608.0,NaN,NaN,NaN,I,NaN,"By Arete Trust, John Kent Walker and Diana Rut...",NaN
3,0001193125-26-135334,8937904,Class C Capital Stock,NaN,27-MAR-2026,NaN,NaN,NaN,4.0,S,...,D,NaN,51808.0,NaN,NaN,NaN,I,NaN,"By Arete Trust, John Kent Walker and Diana Rut...",NaN
4,0001193125-26-135334,8937900,Class C Capital Stock,NaN,27-MAR-2026,NaN,NaN,NaN,4.0,S,...,D,NaN,58124.0,NaN,NaN,NaN,I,NaN,"By Arete Trust, John Kent Walker and Diana Rut...",NaN
5,0001193125-26-135334,8937903,Class C Capital Stock,NaN,27-MAR-2026,NaN,NaN,NaN,4.0,S,...,D,NaN,53108.0,NaN,NaN,NaN,I,NaN,"By Arete Trust, John Kent Walker and Diana Rut...",NaN
6,0001193125-26-135334,8937902,Class C Capital Stock,NaN,27-MAR-2026,NaN,NaN,NaN,4.0,S,...,D,NaN,55208.0,NaN,NaN,NaN,I,NaN,"By Arete Trust, John Kent Walker and Diana Rut...",NaN

In [15]:
# Standarize NOT_SUBJECT_SEC16 in the submission table to real Boolean values
submission['NOT_SUBJECT_SEC16'] = submission['NOT_SUBJECT_SEC16'].replace({
    'false' : False,
    0 : False,
    '0' : False,
    'true' : True,
    1 : True,
    '1' : True

})

submission['NOT_SUBJECT_SEC16'].unique()

array([False, nan, True], dtype=object)